### ISSUE TITLE
16x16 code is using GlobalOffset parameter which is not supported by this pyrometer model

### ISSUE THREAD

**Issue by pwiecz** [HeimannSensor/ESP32_ApplicationShield#1]
https://github.com/HeimannSensor/ESP32_ApplicationShield/blob/231dd43fcf99b282c9ad3ed0a64ef6540449c7ea/ESP32_HTPAd_16x16/ESP32_HTPAd_16x16.ino#L90 defines globaloff variable, which is not initialized anywhere, as it's not a calibration parameter of 16x16 sensor.
Still it is being printed and added to the calculated temperatures.

**Comment by HeimannSensor** [comment]
Thanks for your input. The globaloff is no longer part of the 16x16 sample code.

**Comment by HeimannSensor** [comment]
Thanks for your input. The globaloff is no longer part of the 16x16 sample code.
